openapi: 3.0.3
info:
  title: SAPS API
  version: 0.1.0
  description: Sistema administrativo de productos y servicios API
paths:
  /api/v1/roles/:
    get:
      operationId: api_v1_roles_retrieve
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoleListResponse'
          description: ''
    post:
      operationId: api_v1_roles_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RoleRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/RoleRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/RoleRequest'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseActionResponse'
          description: ''
components:
  schemas:
    BaseActionResponse:
      type: object
      properties:
        message:
          type: string
        content:
          type: boolean
      required:
      - content
      - message
    RoleListResponse:
      type: object
      properties:
        message:
          type: string
        content:
          type: array
          items:
            $ref: '#/components/schemas/Roles'
      required:
      - content
      - message
    RoleRequest:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
      required:
      - name
    Roles:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 20
        description:
          type: string
          nullable: true
          maxLength: 255
      required:
      - id
      - name
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
